### ISSUE TITLE
Where to insert the StreamingAssets folder?

### ISSUE THREAD

**Issue by Foxydroid** [12brendon34/e#1]
I don't understand where the game files folder should be pasted?

**Comment by 12brendon34** [comment]
better to talk on the discord, i just use this for direct links
anyways after attempting to launch once it will automatically make a folder under
Internal Memory > Rain World
in here you can place the StreamingAssets Folder
it will also create a folder called PersistantData where user save data is stored along with console logs and exception logs and lastly a .nomedia file to prevent devices gallery apps from indexing the game textures stored within

sorry for never responding, as I mentioned I do not use this repo for anything but file storage hence the name
I might change it later
